<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MPR Report - {{ $project->prj_code }}</title>
    <style>
        body { font-family: 'Courier New', Courier, monospace; padding: 40px; background: #fff; color: #000; }
        .header { border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; margin-bottom: 10px; }
        .meta { font-size: 14px; margin-bottom: 5px; }
        .section { margin-bottom: 30px; }
        .section-title { font-size: 16px; font-weight: bold; text-decoration: underline; margin-bottom: 10px; text-transform: uppercase; }
        .content { font-size: 14px; line-height: 1.6; white-space: pre-wrap; }
        .footer { margin-top: 50px; font-size: 12px; border-top: 1px dotted #000; padding-top: 10px; }
        .badge { display: inline-block; padding: 2px 8px; border: 1px solid #000; font-size: 12px; font-weight: bold; }
    </style>
</head>
<body>

    <div class="header">
        <div class="title">MONTHLY PROGRESS REPORT (MPR)</div>
        <div class="meta"><strong>Project:</strong> {{ $project->prj_title }} ({{ $project->prj_code }})</div>
        <div class="meta"><strong>Division:</strong> {{ $project->unit->unt_name }}</div>
        <div class="meta"><strong>Report Date:</strong> {{ \Carbon\Carbon::now()->format('d-M-Y') }}</div>
        <div class="meta">
            <strong>Status:</strong> 
            <span class="badge">{{ $document->status }}</span>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Initiator Details</div>
        <div class="meta"><strong>Name:</strong> {{ $initiator->acc_name ?? 'N/A' }}</div>
        <div class="meta"><strong>Role:</strong> {{ $initiator->role->role_name ?? 'Division User' }}</div>
        <div class="meta"><strong>Submitted On:</strong> {{ $latestVersion ? \Carbon\Carbon::parse($latestVersion->created_at)->format('d-M-Y H:i A') : 'N/A' }}</div>
    </div>

    @if($lastAction)
    <div class="section">
        <div class="section-title">Last Action By SORD</div>
        <div class="meta"><strong>Action:</strong> {{ $lastAction->action_type }}</div>
        <div class="meta"><strong>By:</strong> {{ $lastAction->fromUser->role->role_name ?? 'SORD' }}</div>
        <div class="meta"><strong>Date:</strong> {{ \Carbon\Carbon::parse($lastAction->created_at)->format('d-M-Y H:i A') }}</div>
        @if($lastAction->notes)
        <div class="meta" style="margin-top: 5px; font-style: italic;">"{{ $lastAction->notes }}"</div>
        @endif
    </div>
    @endif

    <div class="section">
        <div class="section-title">Physical Progress</div>
        <div class="content">
            {{ $mprData['physical_progress'] ?? 'No physical progress data available.' }}
        </div>
    </div>

    <div class="section">
        <div class="section-title">Financial Progress</div>
        <div class="content">
            {{ $mprData['financial_progress'] ?? 'No financial progress data available.' }}
        </div>
    </div>

    <div class="section">
        <div class="section-title">Issues / Bottlenecks</div>
        <div class="content">
            {{ $mprData['issues'] ?? 'No issues reported.' }}
        </div>
    </div>

    <div class="footer">
        Generated by RDWIS - Water Tanker Monitoring System | {{ \Carbon\Carbon::now()->toDateTimeString() }}
    </div>

    <script>
        window.print();
    </script>
</body>
</html>
