import os
import sys
import shutil
import subprocess

# ==============================================================================
# Database Configuration / ڈیٹا بیس کی ترتیبات
# ==============================================================================
DB_HOST = "127.0.0.1"
DB_PORT = "5433"          # Default port for PostgreSQL 18 in RDWIS
DB_NAME = "updatedrdwV1"
DB_USER = "postgres"
DB_PASSWORD = "12345678"

# ==============================================================================
# Find psql executable / psql ٹول تلاش کرنے کا فنکشن
# ==============================================================================
def find_psql():
    possible_paths = [
        r"C:\Program Files\PostgreSQL\18\bin\psql.exe",
        r"C:\Program Files\PostgreSQL\17\bin\pg_dump.exe",
        r"C:\Program Files\PostgreSQL\16\bin\psql.exe",
        r"C:\Program Files\PostgreSQL\15\bin\psql.exe",
        r"C:\Program Files\PostgreSQL\14\bin\psql.exe",
        r"C:\Program Files\PostgreSQL\13\bin\psql.exe",
    ]
    for path in possible_paths:
        if os.path.isfile(path):
            return path
            
    system_psql = shutil.which("psql")
    if system_psql:
        return system_psql
        
    return "psql"

# ==============================================================================
# SQL Insert Script for superadminrdw
# NOTE: acc_id is an IDENTITY column (GENERATED ALWAYS), so it is omitted
# and PostgreSQL automatically generates the acc_id.
# ==============================================================================
SQL_COMMANDS = """
BEGIN;

-- 1. Insert superadminrdw ONLY if it does not already exist (acc_id is auto-generated)
INSERT INTO cen.accounts (
    acc_unt_id,
    acc_level,
    acc_type,
    acc_reportlevel,
    acc_username,
    acc_pass,
    acc_startdt,
    acc_status,
    acc_enddt,
    acc_name,
    acc_title,
    acc_rank,
    acc_desig,
    acc_desigshort,
    acc_desigtype,
    acc_lowerm,
    acc_upperm,
    acc_access,
    acc_lowers,
    acc_uppers,
    acc_untname,
    acc_untnamesh,
    acc_unttype,
    acc_auth,
    acc_untarea
)
SELECT
    100000,
    25,
    'Admin',
    39,
    'superadminrdw',
    'EiSWEBHWWgVqXiGi896qAWhD9FUMnU+DdZOJkJzIy8kmf2ARiUqROKKnMthyQt8/GpCwMRJ5l8GDQUul5CQgIQ==',
    NOW(),
    'Active',
    NULL,
    'Super Admin',
    NULL,
    'ADMIN USER',
    'System Admin',
    'Sys Admin',
    'lead',
    100000,
    999999,
    'multiple',
    100000,
    999999,
    'Navy Research and Development Institute',
    'NRDI',
    'Institute',
    'approver',
    'it'
WHERE NOT EXISTS (
    SELECT 1 FROM cen.accounts WHERE acc_username = 'superadminrdw'
);

-- 2. If it already exists, ensure its status is Active
UPDATE cen.accounts
SET acc_status = 'Active'
WHERE acc_username = 'superadminrdw';

COMMIT;
"""

def insert_superadmin():
    print("=" * 70)
    print("INSERT SUPERADMINRDW ACCOUNT UTILITY")
    print("=" * 70)
    print(f"Database   : {DB_NAME}")
    print(f"Host:Port  : {DB_HOST}:{DB_PORT}")
    print(f"Username   : {DB_USER}")
    print("Note       : acc_id is AUTO-GENERATED by PostgreSQL (Identity column)")
    
    psql_bin = find_psql()
    print(f"psql Path  : {psql_bin}")
    
    env = os.environ.copy()
    env["PGPASSWORD"] = DB_PASSWORD

    cmd = [
        psql_bin,
        "-h", DB_HOST,
        "-p", DB_PORT,
        "-U", DB_USER,
        "-d", DB_NAME,
        "-v", "ON_ERROR_STOP=1"
    ]

    print("\nExecuting insert script...")
    res = subprocess.run(cmd, env=env, input=SQL_COMMANDS, capture_output=True, text=True)

    if res.returncode != 0:
        print("\n[ERROR] Failed to insert/verify superadminrdw.")
        print(res.stderr)
        return False

    # Verification Query
    verify_sql = """
    SELECT acc_id, acc_username, acc_name, acc_desig, acc_status, acc_untname 
    FROM cen.accounts 
    WHERE acc_username = 'superadminrdw';
    """
    verify_cmd = [psql_bin, "-h", DB_HOST, "-p", DB_PORT, "-U", DB_USER, "-d", DB_NAME, "-c", verify_sql]
    verify_res = subprocess.run(verify_cmd, env=env, capture_output=True, text=True)
    
    print("\n--- ACCOUNT RECORD IN CEN.ACCOUNTS ---")
    print(verify_res.stdout)
    print("[SUCCESS] superadminrdw account is active and verified.")
    print("=" * 70)
    return True


if __name__ == "__main__":
    success = insert_superadmin()
    if not success:
        sys.exit(1)
