--
-- NOTE:
--
-- File paths need to be edited. Search for $$PATH$$ and
-- replace it with the path to the directory containing
-- the extracted data files.
--
--
-- PostgreSQL database dump
--

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE newdev;
--
-- Name: newdev; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE newdev WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE newdev OWNER TO postgres;

\unrestrict (null)
\connect newdev
\restrict (null)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ina; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA ina;


ALTER SCHEMA ina OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: inaattachments; Type: TABLE; Schema: ina; Owner: postgres
--

CREATE TABLE ina.inaattachments (
    iat_objtype character varying NOT NULL,
    iat_objid integer NOT NULL,
    iat_type character varying NOT NULL,
    iat_path character varying,
    iat_id integer NOT NULL
);


ALTER TABLE ina.inaattachments OWNER TO postgres;

--
-- Name: inaattachments_iat_id_seq; Type: SEQUENCE; Schema: ina; Owner: postgres
--

ALTER TABLE ina.inaattachments ALTER COLUMN iat_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME ina.inaattachments_iat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invatcomps; Type: TABLE; Schema: ina; Owner: postgres
--

CREATE TABLE ina.invatcomps (
    iac_id integer NOT NULL,
    iac_ias_id integer NOT NULL,
    iac_qty numeric NOT NULL,
    iac_qtyunit character varying NOT NULL,
    iac_parent_id integer,
    iac_isparent boolean DEFAULT false NOT NULL,
    iac_isassembly boolean DEFAULT false NOT NULL,
    iac_location character varying,
    iac_group character varying,
    iac_person character varying,
    iac_dtg timestamp without time zone NOT NULL,
    iac_dispdate date,
    iac_dispdtg timestamp without time zone,
    iac_status character varying NOT NULL,
    iac_remarks character varying,
    iac_details text,
    iac_shared boolean DEFAULT false NOT NULL
);


ALTER TABLE ina.invatcomps OWNER TO postgres;

--
-- Name: invatcomps_iac_id_seq; Type: SEQUENCE; Schema: ina; Owner: postgres
--

ALTER TABLE ina.invatcomps ALTER COLUMN iac_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME ina.invatcomps_iac_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invatlocs; Type: TABLE; Schema: ina; Owner: postgres
--

CREATE TABLE ina.invatlocs (
    ial_id integer NOT NULL,
    ial_ias_id integer NOT NULL,
    ial_date date NOT NULL,
    ial_unt_id integer NOT NULL,
    ial_location character varying NOT NULL,
    ial_custgroup character varying NOT NULL,
    ial_custperson character varying NOT NULL
);


ALTER TABLE ina.invatlocs OWNER TO postgres;

--
-- Name: invatlocs_ial_id_seq; Type: SEQUENCE; Schema: ina; Owner: postgres
--

ALTER TABLE ina.invatlocs ALTER COLUMN ial_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME ina.invatlocs_ial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invats; Type: TABLE; Schema: ina; Owner: postgres
--

CREATE TABLE ina.invats (
    ias_id integer NOT NULL,
    ias_pcs_id integer,
    ias_pci_id integer,
    ias_desc text NOT NULL,
    ias_details text,
    ias_spec_id integer,
    ias_qty numeric NOT NULL,
    ias_qtyunit character varying NOT NULL,
    ias_unt_id integer NOT NULL,
    ias_prj_id integer,
    ias_effhed_id integer,
    ias_chargedate date NOT NULL,
    ias_price numeric,
    ias_type smallint NOT NULL,
    ias_subtype character varying,
    ias_dtg timestamp without time zone,
    ias_type2 smallint
);


ALTER TABLE ina.invats OWNER TO postgres;

--
-- Name: invats_ias_id_seq; Type: SEQUENCE; Schema: ina; Owner: postgres
--

ALTER TABLE ina.invats ALTER COLUMN ias_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ina.invats_ias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invatspecs; Type: TABLE; Schema: ina; Owner: postgres
--

CREATE TABLE ina.invatspecs (
    iap_ias_id integer NOT NULL,
    iap_specname character varying NOT NULL,
    iap_specvalue character varying NOT NULL
);


ALTER TABLE ina.invatspecs OWNER TO postgres;

--
-- Name: invenitems; Type: TABLE; Schema: ina; Owner: postgres
--

CREATE TABLE ina.invenitems (
    ini_id integer NOT NULL,
    ini_inv_id integer NOT NULL,
    ini_qty numeric NOT NULL,
    ini_qtyunit character varying NOT NULL,
    ini_parent_id integer,
    ini_isparent boolean NOT NULL,
    ini_isassembly boolean NOT NULL,
    ini_location character varying,
    ini_group character varying,
    ini_person character varying,
    ini_dtg timestamp without time zone NOT NULL,
    ini_dispdate date,
    ini_dispdtg timestamp without time zone,
    ini_status character varying NOT NULL,
    ini_remarks character varying
);


ALTER TABLE ina.invenitems OWNER TO postgres;

--
-- Name: inventory; Type: TABLE; Schema: ina; Owner: postgres
--

CREATE TABLE ina.inventory (
    inv_id integer NOT NULL,
    inv_pcs_id integer,
    inv_pci_id integer,
    inv_desc character varying NOT NULL,
    inv_details character varying,
    inv_spec_id integer,
    inv_qty numeric NOT NULL,
    inv_qtyunit character varying NOT NULL,
    inv_unt_id integer NOT NULL,
    inv_chargedate date NOT NULL,
    inv_price numeric,
    inv_type character varying NOT NULL,
    inv_subtype character varying NOT NULL,
    inv_dtg timestamp without time zone,
    inv_prj_id integer
);


ALTER TABLE ina.inventory OWNER TO postgres;

--
-- Data for Name: inaattachments; Type: TABLE DATA; Schema: ina; Owner: postgres
--

COPY ina.inaattachments (iat_objtype, iat_objid, iat_type, iat_path, iat_id) FROM stdin;
\.
COPY ina.inaattachments (iat_objtype, iat_objid, iat_type, iat_path, iat_id) FROM '$$PATH$$/5264.dat';

--
-- Data for Name: invatcomps; Type: TABLE DATA; Schema: ina; Owner: postgres
--

COPY ina.invatcomps (iac_id, iac_ias_id, iac_qty, iac_qtyunit, iac_parent_id, iac_isparent, iac_isassembly, iac_location, iac_group, iac_person, iac_dtg, iac_dispdate, iac_dispdtg, iac_status, iac_remarks, iac_details, iac_shared) FROM stdin;
\.
COPY ina.invatcomps (iac_id, iac_ias_id, iac_qty, iac_qtyunit, iac_parent_id, iac_isparent, iac_isassembly, iac_location, iac_group, iac_person, iac_dtg, iac_dispdate, iac_dispdtg, iac_status, iac_remarks, iac_details, iac_shared) FROM '$$PATH$$/5266.dat';

--
-- Data for Name: invatlocs; Type: TABLE DATA; Schema: ina; Owner: postgres
--

COPY ina.invatlocs (ial_id, ial_ias_id, ial_date, ial_unt_id, ial_location, ial_custgroup, ial_custperson) FROM stdin;
\.
COPY ina.invatlocs (ial_id, ial_ias_id, ial_date, ial_unt_id, ial_location, ial_custgroup, ial_custperson) FROM '$$PATH$$/5268.dat';

--
-- Data for Name: invats; Type: TABLE DATA; Schema: ina; Owner: postgres
--

COPY ina.invats (ias_id, ias_pcs_id, ias_pci_id, ias_desc, ias_details, ias_spec_id, ias_qty, ias_qtyunit, ias_unt_id, ias_prj_id, ias_effhed_id, ias_chargedate, ias_price, ias_type, ias_subtype, ias_dtg, ias_type2) FROM stdin;
\.
COPY ina.invats (ias_id, ias_pcs_id, ias_pci_id, ias_desc, ias_details, ias_spec_id, ias_qty, ias_qtyunit, ias_unt_id, ias_prj_id, ias_effhed_id, ias_chargedate, ias_price, ias_type, ias_subtype, ias_dtg, ias_type2) FROM '$$PATH$$/5270.dat';

--
-- Data for Name: invatspecs; Type: TABLE DATA; Schema: ina; Owner: postgres
--

COPY ina.invatspecs (iap_ias_id, iap_specname, iap_specvalue) FROM stdin;
\.
COPY ina.invatspecs (iap_ias_id, iap_specname, iap_specvalue) FROM '$$PATH$$/5272.dat';

--
-- Data for Name: invenitems; Type: TABLE DATA; Schema: ina; Owner: postgres
--

COPY ina.invenitems (ini_id, ini_inv_id, ini_qty, ini_qtyunit, ini_parent_id, ini_isparent, ini_isassembly, ini_location, ini_group, ini_person, ini_dtg, ini_dispdate, ini_dispdtg, ini_status, ini_remarks) FROM stdin;
\.
COPY ina.invenitems (ini_id, ini_inv_id, ini_qty, ini_qtyunit, ini_parent_id, ini_isparent, ini_isassembly, ini_location, ini_group, ini_person, ini_dtg, ini_dispdate, ini_dispdtg, ini_status, ini_remarks) FROM '$$PATH$$/5273.dat';

--
-- Data for Name: inventory; Type: TABLE DATA; Schema: ina; Owner: postgres
--

COPY ina.inventory (inv_id, inv_pcs_id, inv_pci_id, inv_desc, inv_details, inv_spec_id, inv_qty, inv_qtyunit, inv_unt_id, inv_chargedate, inv_price, inv_type, inv_subtype, inv_dtg, inv_prj_id) FROM stdin;
\.
COPY ina.inventory (inv_id, inv_pcs_id, inv_pci_id, inv_desc, inv_details, inv_spec_id, inv_qty, inv_qtyunit, inv_unt_id, inv_chargedate, inv_price, inv_type, inv_subtype, inv_dtg, inv_prj_id) FROM '$$PATH$$/5274.dat';

--
-- Name: inaattachments_iat_id_seq; Type: SEQUENCE SET; Schema: ina; Owner: postgres
--

SELECT pg_catalog.setval('ina.inaattachments_iat_id_seq', 1, false);


--
-- Name: invatcomps_iac_id_seq; Type: SEQUENCE SET; Schema: ina; Owner: postgres
--

SELECT pg_catalog.setval('ina.invatcomps_iac_id_seq', 8362, true);


--
-- Name: invatlocs_ial_id_seq; Type: SEQUENCE SET; Schema: ina; Owner: postgres
--

SELECT pg_catalog.setval('ina.invatlocs_ial_id_seq', 1, false);


--
-- Name: invats_ias_id_seq; Type: SEQUENCE SET; Schema: ina; Owner: postgres
--

SELECT pg_catalog.setval('ina.invats_ias_id_seq', 13597, true);


--
-- Name: inaattachments intattachments_pk; Type: CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.inaattachments
    ADD CONSTRAINT intattachments_pk PRIMARY KEY (iat_id);


--
-- Name: invatcomps invatcomps_pk; Type: CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.invatcomps
    ADD CONSTRAINT invatcomps_pk PRIMARY KEY (iac_id);


--
-- Name: invatlocs invatlocs_pk; Type: CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.invatlocs
    ADD CONSTRAINT invatlocs_pk PRIMARY KEY (ial_id);


--
-- Name: invats invats_pk; Type: CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.invats
    ADD CONSTRAINT invats_pk PRIMARY KEY (ias_id);


--
-- Name: invatspecs invatspecs_pk; Type: CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.invatspecs
    ADD CONSTRAINT invatspecs_pk PRIMARY KEY (iap_ias_id, iap_specname);


--
-- Name: invenitems invenitems_pk; Type: CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.invenitems
    ADD CONSTRAINT invenitems_pk PRIMARY KEY (ini_id);


--
-- Name: inventory inventory_pk; Type: CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.inventory
    ADD CONSTRAINT inventory_pk PRIMARY KEY (inv_id);


--
-- Name: invatcomps invatcomps_fk; Type: FK CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.invatcomps
    ADD CONSTRAINT invatcomps_fk FOREIGN KEY (iac_ias_id) REFERENCES ina.invats(ias_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: invatlocs invatlocs_fk; Type: FK CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.invatlocs
    ADD CONSTRAINT invatlocs_fk FOREIGN KEY (ial_ias_id) REFERENCES ina.invats(ias_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: invatspecs invatspecs_fk; Type: FK CONSTRAINT; Schema: ina; Owner: postgres
--

ALTER TABLE ONLY ina.invatspecs
    ADD CONSTRAINT invatspecs_fk FOREIGN KEY (iap_ias_id) REFERENCES ina.invats(ias_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

