--
-- NOTE:
--
-- File paths need to be edited. Search for $$PATH$$ and
-- replace it with the path to the directory containing
-- the extracted data files.
--
--
-- PostgreSQL database dump
--

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE newdev;
--
-- Name: newdev; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE newdev WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE newdev OWNER TO postgres;

\unrestrict (null)
\connect newdev
\restrict (null)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: frm; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA frm;


ALTER SCHEMA frm OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: facils; Type: TABLE; Schema: frm; Owner: postgres
--

CREATE TABLE frm.facils (
    fcl_xfrm_id integer NOT NULL,
    fcl_facil character varying(255) NOT NULL
);


ALTER TABLE frm.facils OWNER TO postgres;

--
-- Name: firmz; Type: TABLE; Schema: frm; Owner: postgres
--

CREATE TABLE frm.firmz (
    frm_id integer NOT NULL,
    frm_name character varying NOT NULL,
    frm_entity character varying(255),
    frm_type character varying(255),
    frm_group character varying(255),
    frm_emp integer,
    frm_points integer,
    frm_black boolean,
    frm_notes text,
    frm_id_old integer,
    frm_ntn character varying,
    frm_gst character varying
);


ALTER TABLE frm.firmz OWNER TO postgres;

--
-- Name: firmz_1_frm_id_seq; Type: SEQUENCE; Schema: frm; Owner: postgres
--

ALTER TABLE frm.firmz ALTER COLUMN frm_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME frm.firmz_1_frm_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: info; Type: TABLE; Schema: frm; Owner: postgres
--

CREATE TABLE frm.info (
    inf_xmsc_id integer NOT NULL,
    inf_xmsc_entity character varying(255) NOT NULL,
    inf_type character varying(255) NOT NULL,
    inf_value character varying(255) NOT NULL
);


ALTER TABLE frm.info OWNER TO postgres;

--
-- Name: offices; Type: TABLE; Schema: frm; Owner: postgres
--

CREATE TABLE frm.offices (
    off_id integer NOT NULL,
    off_entity character varying(255),
    off_xfrm_id integer,
    off_name character varying(255),
    off_type character varying(255),
    off_address text,
    off_city character varying(255)
);


ALTER TABLE frm.offices OWNER TO postgres;

--
-- Name: offices_1_off_id_seq; Type: SEQUENCE; Schema: frm; Owner: postgres
--

ALTER TABLE frm.offices ALTER COLUMN off_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME frm.offices_1_off_id_seq
    START WITH 56
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persons; Type: TABLE; Schema: frm; Owner: postgres
--

CREATE TABLE frm.persons (
    per_id integer NOT NULL,
    per_entity character varying(255),
    per_xfrm_id integer,
    per_title character varying(255),
    per_name character varying(50),
    per_desig character varying(255),
    per_dept character varying(255),
    per_exprt character varying(255)
);


ALTER TABLE frm.persons OWNER TO postgres;

--
-- Name: persons_1_per_id_seq; Type: SEQUENCE; Schema: frm; Owner: postgres
--

ALTER TABLE frm.persons ALTER COLUMN per_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME frm.persons_1_per_id_seq
    START WITH 27
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: frm; Owner: postgres
--

CREATE TABLE frm.projects (
    prj_xfrm_id integer NOT NULL,
    prj_name character varying(255) NOT NULL,
    prj_scope character varying(255),
    prj_awarddt timestamp with time zone,
    prj_status character varying(255),
    prj_compdt timestamp with time zone,
    prj_tech character varying(255),
    prj_cost integer
);


ALTER TABLE frm.projects OWNER TO postgres;

--
-- Name: specs; Type: TABLE; Schema: frm; Owner: postgres
--

CREATE TABLE frm.specs (
    spc_xfrm_id integer NOT NULL,
    spc_spec character varying(255) NOT NULL
);


ALTER TABLE frm.specs OWNER TO postgres;

--
-- Data for Name: facils; Type: TABLE DATA; Schema: frm; Owner: postgres
--

COPY frm.facils (fcl_xfrm_id, fcl_facil) FROM stdin;
\.
COPY frm.facils (fcl_xfrm_id, fcl_facil) FROM '$$PATH$$/5265.dat';

--
-- Data for Name: firmz; Type: TABLE DATA; Schema: frm; Owner: postgres
--

COPY frm.firmz (frm_id, frm_name, frm_entity, frm_type, frm_group, frm_emp, frm_points, frm_black, frm_notes, frm_id_old, frm_ntn, frm_gst) FROM stdin;
\.
COPY frm.firmz (frm_id, frm_name, frm_entity, frm_type, frm_group, frm_emp, frm_points, frm_black, frm_notes, frm_id_old, frm_ntn, frm_gst) FROM '$$PATH$$/5266.dat';

--
-- Data for Name: info; Type: TABLE DATA; Schema: frm; Owner: postgres
--

COPY frm.info (inf_xmsc_id, inf_xmsc_entity, inf_type, inf_value) FROM stdin;
\.
COPY frm.info (inf_xmsc_id, inf_xmsc_entity, inf_type, inf_value) FROM '$$PATH$$/5268.dat';

--
-- Data for Name: offices; Type: TABLE DATA; Schema: frm; Owner: postgres
--

COPY frm.offices (off_id, off_entity, off_xfrm_id, off_name, off_type, off_address, off_city) FROM stdin;
\.
COPY frm.offices (off_id, off_entity, off_xfrm_id, off_name, off_type, off_address, off_city) FROM '$$PATH$$/5269.dat';

--
-- Data for Name: persons; Type: TABLE DATA; Schema: frm; Owner: postgres
--

COPY frm.persons (per_id, per_entity, per_xfrm_id, per_title, per_name, per_desig, per_dept, per_exprt) FROM stdin;
\.
COPY frm.persons (per_id, per_entity, per_xfrm_id, per_title, per_name, per_desig, per_dept, per_exprt) FROM '$$PATH$$/5271.dat';

--
-- Data for Name: projects; Type: TABLE DATA; Schema: frm; Owner: postgres
--

COPY frm.projects (prj_xfrm_id, prj_name, prj_scope, prj_awarddt, prj_status, prj_compdt, prj_tech, prj_cost) FROM stdin;
\.
COPY frm.projects (prj_xfrm_id, prj_name, prj_scope, prj_awarddt, prj_status, prj_compdt, prj_tech, prj_cost) FROM '$$PATH$$/5273.dat';

--
-- Data for Name: specs; Type: TABLE DATA; Schema: frm; Owner: postgres
--

COPY frm.specs (spc_xfrm_id, spc_spec) FROM stdin;
\.
COPY frm.specs (spc_xfrm_id, spc_spec) FROM '$$PATH$$/5274.dat';

--
-- Name: firmz_1_frm_id_seq; Type: SEQUENCE SET; Schema: frm; Owner: postgres
--

SELECT pg_catalog.setval('frm.firmz_1_frm_id_seq', 216, true);


--
-- Name: offices_1_off_id_seq; Type: SEQUENCE SET; Schema: frm; Owner: postgres
--

SELECT pg_catalog.setval('frm.offices_1_off_id_seq', 125, true);


--
-- Name: persons_1_per_id_seq; Type: SEQUENCE SET; Schema: frm; Owner: postgres
--

SELECT pg_catalog.setval('frm.persons_1_per_id_seq', 27, true);


--
-- Name: facils facils_pk; Type: CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.facils
    ADD CONSTRAINT facils_pk PRIMARY KEY (fcl_xfrm_id, fcl_facil);


--
-- Name: firmz firmz_pk; Type: CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.firmz
    ADD CONSTRAINT firmz_pk PRIMARY KEY (frm_id);


--
-- Name: firmz firmz_un; Type: CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.firmz
    ADD CONSTRAINT firmz_un UNIQUE (frm_name);


--
-- Name: info info_pk; Type: CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.info
    ADD CONSTRAINT info_pk PRIMARY KEY (inf_xmsc_id, inf_xmsc_entity, inf_type, inf_value);


--
-- Name: offices offices_pk; Type: CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.offices
    ADD CONSTRAINT offices_pk PRIMARY KEY (off_id);


--
-- Name: persons persons_pk; Type: CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.persons
    ADD CONSTRAINT persons_pk PRIMARY KEY (per_id);


--
-- Name: projects projects_pk; Type: CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.projects
    ADD CONSTRAINT projects_pk PRIMARY KEY (prj_xfrm_id, prj_name);


--
-- Name: specs specs_pk; Type: CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.specs
    ADD CONSTRAINT specs_pk PRIMARY KEY (spc_xfrm_id, spc_spec);


--
-- Name: facils facils_fk; Type: FK CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.facils
    ADD CONSTRAINT facils_fk FOREIGN KEY (fcl_xfrm_id) REFERENCES frm.firmz(frm_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: offices offices_fk; Type: FK CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.offices
    ADD CONSTRAINT offices_fk FOREIGN KEY (off_xfrm_id) REFERENCES frm.firmz(frm_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: persons persons_fk; Type: FK CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.persons
    ADD CONSTRAINT persons_fk FOREIGN KEY (per_xfrm_id) REFERENCES frm.firmz(frm_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: projects projects_fk; Type: FK CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.projects
    ADD CONSTRAINT projects_fk FOREIGN KEY (prj_xfrm_id) REFERENCES frm.firmz(frm_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: specs specs_fk; Type: FK CONSTRAINT; Schema: frm; Owner: postgres
--

ALTER TABLE ONLY frm.specs
    ADD CONSTRAINT specs_fk FOREIGN KEY (spc_xfrm_id) REFERENCES frm.firmz(frm_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

